### ISSUE TITLE
CompileException: Unknown variable or type "FunctionHelpersXL".

### ISSUE THREAD

**Issue by bigfacewo** [sheinbergon/dremio-udf-gis#5] opened 2022-04-27 06:57 UTC
Dremio was compiled in "JDK1.8", so I tried to compile "dremio-udf-gis" myself.

After modifying part of the code, I'm in jdk1.8 compilation succeeded. Removed unsupported syntax in 1.8.

But in actual use, it is wrong:

![20220427-145038](https://user-images.githubusercontent.com/31603897/165458503-141c6ffb-f827-4039-ab22-6aec730e5158.png)

**Comment by sheinbergon** [comment] 2022-04-27 11:25
Hi @bigfacewo.

First of all, you can just run Dremio compiled for JDK8 with this jar  under JDK11 and it'll work. You don't need to compile anything for JDK 11 on your own.

Second, when you changed the code, you probably didn't include full path import (like anyone would do).

If you look at the source code - it includes full path. That's due to how dremio parses/compiles UDF - in real time, requiring full paths to be included inside the source code. That's why you're getting this error.

**Comment by sheinbergon** [comment] 2022-04-27 11:27
Also note that the supported input format (for now) is WKT, not WKB

**Comment by sheinbergon** [comment] 2022-04-27 11:38
A future release will include an adaptation of this function:

https://postgis.net/docs/ST_GeomFromWKB.html

**Comment by sheinbergon** [comment] 2022-04-27 22:45
1) `ST_GeomFromText` expects WKT, not WKB
2) If you'd like to send me a sample data set, I'll happily go over it
3) The error indicates some live compilation issue (Dremio compiles the source code from scratch). I did not encounter these issues in the cluster I'm running this extension on. Care to share more details about your setup?

**Comment by sheinbergon** [comment] 2022-04-27 23:06
Duplicate of #6 . I'm closing this issue. let's follow up there

**Closed** 2022-04-27 23:06 UTC
Labels: duplicate

**Comment by sheinbergon** [comment] 2022-04-29 19:23
@bigfacewo JIC - See updates [here](https://github.com/sheinbergon/dremio-udf-gis/issues/6#issuecomment-1113646229). 
Please try it out and let me know.

10x

**Comment by sheinbergon** [comment] 2022-05-03 14:12
@bigfacewo have you gotten round to testing the new version in [here](https://github.com/sheinbergon/dremio-udf-gis/issues/6#issuecomment-1113646229)

**Comment by sheinbergon** [comment] 2022-05-05 22:21
@bigfacewo release 0.2.3 should address your concerns.

**Comment by bigfacewo** [comment] 2022-05-09 02:15
@sheinbergon It‘s working.
Thank you. You have done a great job.

**Comment by sheinbergon** [comment] 2022-05-09 06:55
No problem. Aside from documentation, would love to hear about missing/desired `ST_*` functions you'd like me to add (Separate issues, of course).
